name: CI
on:
  push:
    branches:
    - main
jobs:
  split-upm:
    name: split upm branch (force)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: split upm branch
      run: |
        git branch -d upm &> /dev/null || echo upm branch not found      
        if [[ -d "Editor/Samples" ]]; then
          git mv Editor/Samples Editor/Samples~
          rm -f Editor/Samples.meta
          rm -rf _Internal
          rm -rf _Internal.meta
          git config --global user.name 'github-bot'
          git config --global user.email 'github-bot@users.noreply.github.com'
          git commit -am "fix: Samples => Samples~"
        fi
        git subtree split -P "Assets" -b upm        
        git push -f -u origin upm