name: CI
on:
  push:
    branches:
    - main
jobs:
  split-upm:
    name: split upm branch (force)
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: split upm branch
      run: |
        git config --global user.name 'github-bot'
        git config --global user.email 'github-bot@users.noreply.github.com'
        git branch -d staging &> /dev/null || echo staging branch not found      
        git checkout staging 
        git merge --no-ff --no-commit main 
        if [[ -d "Assets/Editor/Samples" ]]; then
          git mv Assets/Editor/Samples Editor/Samples~
          rm -f Assets/Editor/Samples.meta
          rm -rf Assets/_Internal
          rm -rf Assets/_Internal.meta
        fi
        git commit -am "fix: Samples => Samples~"
        git push -f -u origin staging
        git branch -d upm &> /dev/null || echo upm branch not found
        git subtree split -P "Assets" -b upm
        git push -f -u origin upm